I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/storetest2.rpy", line 3, in script
    init python:
  File "game/storetest2.rpy", line 27, in <module>
    about_ach2 = EncEntry(
TypeError: __init__() got an unexpected keyword argument 'note'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/storetest2.rpy", line 3, in script
    init python:
  File "D:\Visunov\renpy-8.1.3-sdk\renpy-8.1.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Visunov\renpy-8.1.3-sdk\renpy-8.1.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/storetest2.rpy", line 27, in <module>
    about_ach2 = EncEntry(
TypeError: __init__() got an unexpected keyword argument 'note'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Test von Sakura 1.090
Mon Oct  7 11:27:36 2024
